services:
  docs:
    container_name: 'ph-address-intel-docs'
    build:
      context: .
      dockerfile: docs/Dockerfile
    ports:
      - "8091:80"
    restart: unless-stopped
    networks:
      - proxy_manager_net

networks:
  proxy_manager_net:
    name: proxy_manager_net
    driver: bridge
