services:
  docs:
    container_name: 'ph-address-intel-docs'
    build:
      context: .
      dockerfile: docs/Dockerfile
    ports:
      - "8091:80"
    restart: unless-stopped
    networks:
      - ph-address-intel-network
      - proxy-network

networks:
  ph-address-intel-network: 
  proxy-network:
    external: true

